services:
  formatif-dev-container-v9:
    container_name: formatif-dev-container-v9
    image: lmsdoubtfire/formatif-devcontainer:9-dev
    build:
      context: ../
      dockerfile: dev.Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached
      - formatif-v9-tmp:/workspace/tmp
      - formatif-v9-student-work:/student-work
      - formatif-v9-web-node_modules:/workspace/doubtfire-web/node_modules
      - formatif-v9-gems:/home/vscode/.gems
    ports:
      - "9876:9876"
      - "4200:4200"
      - "3000:3000"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 5000; do :; done"
    env_file:
      - devcontainer.env
    depends_on:
      - dev-db-v9
  dev-db-v9:
    container_name: doubtfire-dev-db-v9
    image: mariadb:10
    restart: always
    volumes:
      - formatif-v9-dev-database:/var/lib/mysql
    env_file:
      - devcontainer.env

volumes:
  formatif-v9-tmp:
  formatif-v9-student-work:
  formatif-v9-web-node_modules:
  formatif-v9-dev-database:
  formatif-v9-gems:
